"""Writes src/main/resources/assets/keycps/lang/*.json. Edit the tables here, then run: python3 tools/gen_lang.py"""
import json, pathlib

KEYS = ["cat", "open_config", "move_hud", "toggle_hud", "title",
        "enabled", "scale", "movement", "jump", "mouse", "cps", "sneak_sprint", "key_rates", "cps_warn",
        "background", "bg_opacity", "bg_color", "text_color", "pressed_color", "rounded", "shadow", "fade", "rainbow",
        "mouse_labels", "move", "reset",
        "t_enabled", "t_scale", "t_movement", "t_jump", "t_mouse", "t_cps", "t_sneak_sprint", "t_key_rates", "t_cps_warn",
        "t_background", "t_bg_opacity", "t_rounded", "t_shadow", "t_fade", "t_rainbow", "t_mouse_labels", "t_move", "t_color",
        "move_hint", "welcome",
        "white", "black", "gray", "red", "orange", "yellow", "lime", "green", "aqua", "blue", "purple", "pink"]

L = {
"en_us": ["KeyCPS", "Open Settings", "Move HUD", "Toggle HUD", "KeyCPS Settings",
  "Show HUD", "Size", "WASD Keys", "Jump Bar", "Attack / Use", "CPS Counter", "Sneak / Sprint", "Rate on Every Key", "CPS Warning",
  "Background", "BG Opacity", "BG Color", "Text Color", "Pressed Color", "Rounded Corners", "Text Shadow", "Press Animation", "Rainbow Text", "Always LMB / RMB",
  "Move HUD", "Reset All",
  "Show or hide the whole overlay.", "How big the HUD is drawn.", "Show the W, A, S and D keys.", "Show the jump key as a bar.",
  "Show the attack and use buttons.", "Show clicks per second inside the attack and use buttons.", "Show a row with your sneak and sprint keys.",
  "Show how often each movement key fires per second. Holding a key counts the keyboard repeat rate.",
  "The CPS counter turns red at this many clicks per second.",
  "Draw a box behind each key.", "How see-through the key boxes are.", "Cut the corners of each key.", "Draw a shadow under the text.",
  "Fade keys smoothly in and out when pressed.", "Cycle the text through the rainbow.", "Label the attack and use keys LMB and RMB even when they're bound to keyboard keys. The CPS still counts those keys, key repeat included.",
  "Drag the HUD anywhere. It snaps to the edges and centre.", "Click to cycle through colours.",
  "Drag the HUD • Esc to save", "[KeyCPS] Press %s to customise the HUD (or use Mod Menu).",
  "White", "Black", "Gray", "Red", "Orange", "Yellow", "Lime", "Green", "Aqua", "Blue", "Purple", "Pink"],
"de_de": ["KeyCPS", "Einstellungen öffnen", "HUD verschieben", "HUD umschalten", "KeyCPS-Einstellungen",
  "HUD anzeigen", "Größe", "WASD-Tasten", "Sprungleiste", "Angriff / Benutzen", "CPS-Zähler", "Schleichen / Sprinten", "Rate pro Taste", "CPS-Warnung",
  "Hintergrund", "Deckkraft", "Hintergrundfarbe", "Textfarbe", "Gedrückt-Farbe", "Runde Ecken", "Textschatten", "Drück-Animation", "Regenbogentext", "Immer LMB / RMB",
  "HUD verschieben", "Alles zurücksetzen",
  "Das gesamte Overlay ein- oder ausblenden.", "Wie groß das HUD gezeichnet wird.", "Die Tasten W, A, S und D anzeigen.", "Die Sprungtaste als Leiste anzeigen.",
  "Angriffs- und Benutzen-Taste anzeigen.", "Klicks pro Sekunde in den Angriffs- und Benutzen-Tasten anzeigen.", "Eine Zeile mit Schleich- und Sprinttaste anzeigen.",
  "Zeigt, wie oft jede Bewegungstaste pro Sekunde auslöst. Gedrückt halten zählt die Tastenwiederholrate.",
  "Ab so vielen Klicks pro Sekunde wird der CPS-Zähler rot.",
  "Einen Kasten hinter jede Taste zeichnen.", "Wie durchsichtig die Tastenkästen sind.", "Die Ecken jeder Taste abrunden.", "Einen Schatten unter den Text zeichnen.",
  "Tasten beim Drücken sanft ein- und ausblenden.", "Den Text in Regenbogenfarben wechseln lassen.", "Angriffs- und Benutzen-Taste immer als LMB und RMB beschriften, auch wenn sie auf der Tastatur liegen. Die CPS zählen trotzdem diese Tasten, inklusive Tastenwiederholung.",
  "Das HUD beliebig verschieben. Es rastet an Rändern und Mitte ein.", "Klicken, um die Farbe zu wechseln.",
  "HUD ziehen • Esc zum Speichern", "[KeyCPS] Drücke %s, um das HUD anzupassen (oder nutze Mod Menu).",
  "Weiß", "Schwarz", "Grau", "Rot", "Orange", "Gelb", "Hellgrün", "Grün", "Türkis", "Blau", "Lila", "Pink"],
"fr_fr": ["KeyCPS", "Ouvrir les paramètres", "Déplacer le HUD", "Afficher/masquer le HUD", "Paramètres KeyCPS",
  "Afficher le HUD", "Taille", "Touches ZQSD", "Barre de saut", "Attaque / Utiliser", "Compteur CPS", "S'accroupir / Sprint", "Fréquence par touche", "Alerte CPS",
  "Fond", "Opacité du fond", "Couleur du fond", "Couleur du texte", "Couleur appuyée", "Coins arrondis", "Ombre du texte", "Animation", "Texte arc-en-ciel", "Toujours LMB / RMB",
  "Déplacer le HUD", "Tout réinitialiser",
  "Afficher ou masquer tout l'overlay.", "Taille d'affichage du HUD.", "Afficher les touches de déplacement.", "Afficher la touche de saut sous forme de barre.",
  "Afficher les boutons d'attaque et d'utilisation.", "Afficher les clics par seconde dans les boutons d'attaque et d'utilisation.", "Afficher une ligne avec les touches s'accroupir et sprint.",
  "Affiche combien de fois chaque touche se déclenche par seconde. Maintenir une touche compte la répétition du clavier.",
  "Le compteur CPS devient rouge à partir de ce nombre de clics par seconde.",
  "Dessiner un fond derrière chaque touche.", "Transparence des fonds de touche.", "Arrondir les coins de chaque touche.", "Dessiner une ombre sous le texte.",
  "Animer les touches en douceur quand elles sont pressées.", "Faire défiler le texte dans les couleurs de l'arc-en-ciel.", "Affiche LMB et RMB sur les touches d'attaque et d'utilisation même si elles sont sur le clavier. Les CPS comptent toujours ces touches, répétition comprise.",
  "Déplacez le HUD n'importe où. Il s'aimante aux bords et au centre.", "Cliquez pour changer de couleur.",
  "Faites glisser le HUD • Échap pour enregistrer", "[KeyCPS] Appuyez sur %s pour personnaliser le HUD (ou utilisez Mod Menu).",
  "Blanc", "Noir", "Gris", "Rouge", "Orange", "Jaune", "Vert clair", "Vert", "Cyan", "Bleu", "Violet", "Rose"],
"es_es": ["KeyCPS", "Abrir ajustes", "Mover HUD", "Mostrar/ocultar HUD", "Ajustes de KeyCPS",
  "Mostrar HUD", "Tamaño", "Teclas WASD", "Barra de salto", "Atacar / Usar", "Contador CPS", "Agacharse / Correr", "Frecuencia por tecla", "Aviso de CPS",
  "Fondo", "Opacidad del fondo", "Color del fondo", "Color del texto", "Color al pulsar", "Esquinas redondeadas", "Sombra del texto", "Animación", "Texto arcoíris", "Siempre LMB / RMB",
  "Mover HUD", "Restablecer todo",
  "Muestra u oculta todo el overlay.", "Tamaño con el que se dibuja el HUD.", "Muestra las teclas W, A, S y D.", "Muestra la tecla de salto como una barra.",
  "Muestra los botones de atacar y usar.", "Muestra los clics por segundo dentro de los botones de atacar y usar.", "Muestra una fila con las teclas de agacharse y correr.",
  "Muestra cuántas veces se activa cada tecla por segundo. Mantener una tecla cuenta la repetición del teclado.",
  "El contador CPS se vuelve rojo a partir de estos clics por segundo.",
  "Dibuja un fondo detrás de cada tecla.", "Transparencia de los fondos de las teclas.", "Redondea las esquinas de cada tecla.", "Dibuja una sombra bajo el texto.",
  "Las teclas se iluminan y apagan suavemente.", "El texto recorre los colores del arcoíris.", "Muestra LMB y RMB en atacar y usar aunque estén en teclas del teclado. Los CPS siguen contando esas teclas, incluida la repetición.",
  "Arrastra el HUD a cualquier sitio. Se ajusta a los bordes y al centro.", "Haz clic para cambiar de color.",
  "Arrastra el HUD • Esc para guardar", "[KeyCPS] Pulsa %s para personalizar el HUD (o usa Mod Menu).",
  "Blanco", "Negro", "Gris", "Rojo", "Naranja", "Amarillo", "Lima", "Verde", "Aguamarina", "Azul", "Morado", "Rosa"],
"pt_br": ["KeyCPS", "Abrir configurações", "Mover HUD", "Mostrar/ocultar HUD", "Configurações do KeyCPS",
  "Mostrar HUD", "Tamanho", "Teclas WASD", "Barra de pulo", "Atacar / Usar", "Contador de CPS", "Agachar / Correr", "Taxa por tecla", "Aviso de CPS",
  "Fundo", "Opacidade do fundo", "Cor do fundo", "Cor do texto", "Cor pressionada", "Cantos arredondados", "Sombra do texto", "Animação", "Texto arco-íris", "Sempre LMB / RMB",
  "Mover HUD", "Redefinir tudo",
  "Mostra ou oculta todo o overlay.", "O tamanho em que o HUD é desenhado.", "Mostra as teclas W, A, S e D.", "Mostra a tecla de pulo como uma barra.",
  "Mostra os botões de atacar e usar.", "Mostra os cliques por segundo dentro dos botões de atacar e usar.", "Mostra uma linha com as teclas de agachar e correr.",
  "Mostra quantas vezes cada tecla dispara por segundo. Segurar uma tecla conta a repetição do teclado.",
  "O contador de CPS fica vermelho a partir desses cliques por segundo.",
  "Desenha um fundo atrás de cada tecla.", "Transparência dos fundos das teclas.", "Arredonda os cantos de cada tecla.", "Desenha uma sombra sob o texto.",
  "As teclas acendem e apagam suavemente.", "O texto passa pelas cores do arco-íris.", "Mostra LMB e RMB em atacar e usar mesmo quando estão em teclas do teclado. O CPS continua contando essas teclas, incluindo a repetição.",
  "Arraste o HUD para qualquer lugar. Ele se alinha às bordas e ao centro.", "Clique para trocar de cor.",
  "Arraste o HUD • Esc para salvar", "[KeyCPS] Pressione %s para personalizar o HUD (ou use o Mod Menu).",
  "Branco", "Preto", "Cinza", "Vermelho", "Laranja", "Amarelo", "Lima", "Verde", "Ciano", "Azul", "Roxo", "Rosa"],
"it_it": ["KeyCPS", "Apri impostazioni", "Sposta HUD", "Mostra/nascondi HUD", "Impostazioni KeyCPS",
  "Mostra HUD", "Dimensione", "Tasti WASD", "Barra salto", "Attacca / Usa", "Contatore CPS", "Accovacciati / Scatta", "Frequenza per tasto", "Avviso CPS",
  "Sfondo", "Opacità sfondo", "Colore sfondo", "Colore testo", "Colore premuto", "Angoli arrotondati", "Ombra testo", "Animazione", "Testo arcobaleno", "Sempre LMB / RMB",
  "Sposta HUD", "Ripristina tutto",
  "Mostra o nasconde l'intero overlay.", "Quanto è grande l'HUD.", "Mostra i tasti W, A, S e D.", "Mostra il tasto salto come barra.",
  "Mostra i pulsanti attacca e usa.", "Mostra i clic al secondo nei pulsanti attacca e usa.", "Mostra una riga con i tasti accovacciati e scatta.",
  "Mostra quante volte ogni tasto scatta al secondo. Tenere premuto un tasto conta la ripetizione della tastiera.",
  "Il contatore CPS diventa rosso da questo numero di clic al secondo.",
  "Disegna uno sfondo dietro ogni tasto.", "Trasparenza degli sfondi dei tasti.", "Arrotonda gli angoli di ogni tasto.", "Disegna un'ombra sotto il testo.",
  "I tasti si illuminano e si spengono dolcemente.", "Il testo scorre tra i colori dell'arcobaleno.", "Mostra LMB e RMB su attacca e usa anche se sono su tasti della tastiera. I CPS contano comunque quei tasti, ripetizione inclusa.",
  "Trascina l'HUD dove vuoi. Si aggancia ai bordi e al centro.", "Clicca per cambiare colore.",
  "Trascina l'HUD • Esc per salvare", "[KeyCPS] Premi %s per personalizzare l'HUD (o usa Mod Menu).",
  "Bianco", "Nero", "Grigio", "Rosso", "Arancione", "Giallo", "Lime", "Verde", "Acqua", "Blu", "Viola", "Rosa"],
"nl_nl": ["KeyCPS", "Instellingen openen", "HUD verplaatsen", "HUD aan/uit", "KeyCPS-instellingen",
  "HUD tonen", "Grootte", "WASD-toetsen", "Springbalk", "Aanvallen / Gebruiken", "CPS-teller", "Sluipen / Sprinten", "Tempo per toets", "CPS-waarschuwing",
  "Achtergrond", "Dekking", "Achtergrondkleur", "Tekstkleur", "Ingedrukt-kleur", "Ronde hoeken", "Tekstschaduw", "Animatie", "Regenboogtekst", "Altijd LMB / RMB",
  "HUD verplaatsen", "Alles resetten",
  "Toon of verberg de hele overlay.", "Hoe groot de HUD getekend wordt.", "Toon de toetsen W, A, S en D.", "Toon de springtoets als balk.",
  "Toon de aanval- en gebruikknop.", "Toon kliks per seconde in de aanval- en gebruikknop.", "Toon een rij met sluip- en sprinttoets.",
  "Toont hoe vaak elke toets per seconde afgaat. Een toets vasthouden telt de toetsherhaling.",
  "De CPS-teller wordt rood vanaf dit aantal kliks per seconde.",
  "Teken een vak achter elke toets.", "Hoe doorzichtig de toetsvakken zijn.", "Rond de hoeken van elke toets af.", "Teken een schaduw onder de tekst.",
  "Toetsen vloeiend laten oplichten en uitfaden.", "Laat de tekst door de regenboog kleuren.", "Toon LMB en RMB op aanvallen en gebruiken, ook als ze op toetsenbordtoetsen staan. De CPS telt die toetsen nog steeds, inclusief herhaling.",
  "Sleep de HUD overal heen. Hij klikt vast aan randen en midden.", "Klik om van kleur te wisselen.",
  "Sleep de HUD • Esc om op te slaan", "[KeyCPS] Druk op %s om de HUD aan te passen (of gebruik Mod Menu).",
  "Wit", "Zwart", "Grijs", "Rood", "Oranje", "Geel", "Limoen", "Groen", "Aqua", "Blauw", "Paars", "Roze"],
"pl_pl": ["KeyCPS", "Otwórz ustawienia", "Przesuń HUD", "Pokaż/ukryj HUD", "Ustawienia KeyCPS",
  "Pokaż HUD", "Rozmiar", "Klawisze WASD", "Pasek skoku", "Atak / Użyj", "Licznik CPS", "Skradanie / Sprint", "Tempo każdego klawisza", "Ostrzeżenie CPS",
  "Tło", "Krycie tła", "Kolor tła", "Kolor tekstu", "Kolor wciśnięcia", "Zaokrąglone rogi", "Cień tekstu", "Animacja", "Tęczowy tekst", "Zawsze LMB / RMB",
  "Przesuń HUD", "Resetuj wszystko",
  "Pokaż lub ukryj całą nakładkę.", "Jak duży jest HUD.", "Pokaż klawisze W, A, S i D.", "Pokaż klawisz skoku jako pasek.",
  "Pokaż przyciski ataku i użycia.", "Pokaż kliknięcia na sekundę w przyciskach ataku i użycia.", "Pokaż rząd z klawiszami skradania i sprintu.",
  "Pokazuje, ile razy na sekundę działa każdy klawisz. Przytrzymanie liczy powtarzanie klawiatury.",
  "Licznik CPS zmienia kolor na czerwony od tej liczby kliknięć na sekundę.",
  "Rysuj tło za każdym klawiszem.", "Przezroczystość tła klawiszy.", "Zaokrąglij rogi każdego klawisza.", "Rysuj cień pod tekstem.",
  "Płynnie podświetlaj i wygaszaj klawisze.", "Tekst przechodzi przez kolory tęczy.", "Podpisuj atak i użycie jako LMB i RMB, nawet gdy są na klawiaturze. CPS nadal liczy te klawisze, łącznie z powtarzaniem.",
  "Przeciągnij HUD w dowolne miejsce. Przyciąga się do krawędzi i środka.", "Kliknij, aby zmienić kolor.",
  "Przeciągnij HUD • Esc, aby zapisać", "[KeyCPS] Naciśnij %s, aby dostosować HUD (lub użyj Mod Menu).",
  "Biały", "Czarny", "Szary", "Czerwony", "Pomarańczowy", "Żółty", "Limonkowy", "Zielony", "Morski", "Niebieski", "Fioletowy", "Różowy"],
"tr_tr": ["KeyCPS", "Ayarları aç", "HUD'u taşı", "HUD'u aç/kapat", "KeyCPS Ayarları",
  "HUD'u göster", "Boyut", "WASD tuşları", "Zıplama çubuğu", "Saldır / Kullan", "CPS sayacı", "Eğil / Koş", "Tuş başına hız", "CPS uyarısı",
  "Arka plan", "Arka plan opaklığı", "Arka plan rengi", "Yazı rengi", "Basılı rengi", "Yuvarlak köşeler", "Yazı gölgesi", "Animasyon", "Gökkuşağı yazı", "Her zaman LMB / RMB",
  "HUD'u taşı", "Hepsini sıfırla",
  "Tüm katmanı göster veya gizle.", "HUD'un ne kadar büyük çizileceği.", "W, A, S ve D tuşlarını göster.", "Zıplama tuşunu çubuk olarak göster.",
  "Saldır ve kullan düğmelerini göster.", "Saldır ve kullan düğmelerinde saniyedeki tıklamayı göster.", "Eğilme ve koşma tuşlarıyla bir satır göster.",
  "Her tuşun saniyede kaç kez tetiklendiğini gösterir. Tuşu basılı tutmak klavye tekrarını sayar.",
  "CPS sayacı bu tıklama hızında kırmızıya döner.",
  "Her tuşun arkasına bir kutu çiz.", "Tuş kutularının saydamlığı.", "Her tuşun köşelerini yuvarla.", "Yazının altına gölge çiz.",
  "Tuşlar basıldığında yumuşakça parlasın.", "Yazı gökkuşağı renklerinde dönsün.", "Saldır ve kullan tuşları klavyede olsa bile LMB ve RMB yazsın. CPS yine de bu tuşları, tekrarlar dahil sayar.",
  "HUD'u istediğin yere sürükle. Kenarlara ve merkeze yapışır.", "Rengi değiştirmek için tıkla.",
  "HUD'u sürükle • Kaydetmek için Esc", "[KeyCPS] HUD'u özelleştirmek için %s tuşuna bas (veya Mod Menu kullan).",
  "Beyaz", "Siyah", "Gri", "Kırmızı", "Turuncu", "Sarı", "Açık yeşil", "Yeşil", "Turkuaz", "Mavi", "Mor", "Pembe"],
"ru_ru": ["KeyCPS", "Открыть настройки", "Переместить HUD", "Показать/скрыть HUD", "Настройки KeyCPS",
  "Показывать HUD", "Размер", "Клавиши WASD", "Полоса прыжка", "Атака / Использ.", "Счётчик CPS", "Присесть / Бег", "Частота клавиш", "Порог CPS",
  "Фон", "Прозрачность фона", "Цвет фона", "Цвет текста", "Цвет нажатия", "Скруглённые углы", "Тень текста", "Анимация", "Радужный текст", "Всегда LMB / RMB",
  "Переместить HUD", "Сбросить всё",
  "Показать или скрыть весь оверлей.", "Размер HUD на экране.", "Показывать клавиши W, A, S и D.", "Показывать прыжок в виде полосы.",
  "Показывать кнопки атаки и использования.", "Показывать клики в секунду в кнопках атаки и использования.", "Показывать ряд с клавишами приседания и бега.",
  "Показывает, сколько раз в секунду срабатывает каждая клавиша. Удержание считает автоповтор клавиатуры.",
  "Счётчик CPS становится красным при таком числе кликов в секунду.",
  "Рисовать фон за каждой клавишей.", "Прозрачность фона клавиш.", "Скруглять углы клавиш.", "Рисовать тень под текстом.",
  "Плавная подсветка клавиш при нажатии.", "Текст переливается цветами радуги.", "Подписывать атаку и использование как LMB и RMB, даже если они на клавиатуре. CPS всё равно считает эти клавиши, включая автоповтор.",
  "Перетащите HUD куда угодно. Он прилипает к краям и центру.", "Нажмите, чтобы сменить цвет.",
  "Перетащите HUD • Esc — сохранить", "[KeyCPS] Нажмите %s, чтобы настроить HUD (или используйте Mod Menu).",
  "Белый", "Чёрный", "Серый", "Красный", "Оранжевый", "Жёлтый", "Лаймовый", "Зелёный", "Бирюзовый", "Синий", "Фиолетовый", "Розовый"],
"uk_ua": ["KeyCPS", "Відкрити налаштування", "Перемістити HUD", "Показати/сховати HUD", "Налаштування KeyCPS",
  "Показувати HUD", "Розмір", "Клавіші WASD", "Смуга стрибка", "Атака / Використ.", "Лічильник CPS", "Присісти / Біг", "Частота клавіш", "Поріг CPS",
  "Фон", "Прозорість фону", "Колір фону", "Колір тексту", "Колір натискання", "Заокруглені кути", "Тінь тексту", "Анімація", "Райдужний текст", "Завжди LMB / RMB",
  "Перемістити HUD", "Скинути все",
  "Показати або сховати весь оверлей.", "Розмір HUD на екрані.", "Показувати клавіші W, A, S і D.", "Показувати стрибок у вигляді смуги.",
  "Показувати кнопки атаки й використання.", "Показувати кліки за секунду в кнопках атаки й використання.", "Показувати ряд із клавішами присідання та бігу.",
  "Показує, скільки разів за секунду спрацьовує кожна клавіша. Утримання рахує автоповтор клавіатури.",
  "Лічильник CPS стає червоним за такої кількості кліків за секунду.",
  "Малювати фон за кожною клавішею.", "Прозорість фону клавіш.", "Заокруглювати кути клавіш.", "Малювати тінь під текстом.",
  "Плавне підсвічування клавіш під час натискання.", "Текст переливається кольорами веселки.", "Підписувати атаку й використання як LMB і RMB, навіть якщо вони на клавіатурі. CPS усе одно рахує ці клавіші, включно з автоповтором.",
  "Перетягніть HUD будь-куди. Він прилипає до країв і центру.", "Натисніть, щоб змінити колір.",
  "Перетягніть HUD • Esc — зберегти", "[KeyCPS] Натисніть %s, щоб налаштувати HUD (або скористайтеся Mod Menu).",
  "Білий", "Чорний", "Сірий", "Червоний", "Помаранчевий", "Жовтий", "Лаймовий", "Зелений", "Бірюзовий", "Синій", "Фіолетовий", "Рожевий"],
"zh_cn": ["KeyCPS", "打开设置", "移动 HUD", "显示/隐藏 HUD", "KeyCPS 设置",
  "显示 HUD", "大小", "WASD 按键", "跳跃条", "攻击 / 使用", "CPS 计数", "潜行 / 疾跑", "每键频率", "CPS 警告",
  "背景", "背景不透明度", "背景颜色", "文字颜色", "按下颜色", "圆角", "文字阴影", "按键动画", "彩虹文字", "始终显示 LMB / RMB",
  "移动 HUD", "全部重置",
  "显示或隐藏整个界面。", "HUD 的显示大小。", "显示 W、A、S、D 键。", "以横条显示跳跃键。",
  "显示攻击和使用按钮。", "在攻击和使用按钮内显示每秒点击数。", "显示潜行和疾跑键一行。",
  "显示每个按键每秒触发的次数。按住按键会计入键盘重复速率。",
  "每秒点击数达到该值时 CPS 计数变红。",
  "在每个按键后绘制背景。", "按键背景的透明度。", "将每个按键的角变圆。", "在文字下绘制阴影。",
  "按下时按键平滑地亮起和熄灭。", "文字循环显示彩虹颜色。", "即使攻击和使用绑定在键盘按键上，也显示为 LMB 和 RMB。CPS 仍会统计这些按键，包括按键重复。",
  "将 HUD 拖到任意位置，会吸附到边缘和中心。", "点击切换颜色。",
  "拖动 HUD • 按 Esc 保存", "[KeyCPS] 按 %s 自定义 HUD（或使用 Mod Menu）。",
  "白色", "黑色", "灰色", "红色", "橙色", "黄色", "黄绿色", "绿色", "青色", "蓝色", "紫色", "粉色"],
"ja_jp": ["KeyCPS", "設定を開く", "HUD を移動", "HUD 表示切替", "KeyCPS 設定",
  "HUD を表示", "サイズ", "WASD キー", "ジャンプバー", "攻撃 / 使用", "CPS カウンター", "スニーク / ダッシュ", "キーごとの回数", "CPS 警告",
  "背景", "背景の不透明度", "背景色", "文字色", "押下時の色", "角丸", "文字の影", "押下アニメ", "虹色の文字", "常に LMB / RMB",
  "HUD を移動", "すべてリセット",
  "オーバーレイ全体の表示/非表示。", "HUD の表示サイズ。", "W・A・S・D キーを表示します。", "ジャンプキーをバーで表示します。",
  "攻撃と使用ボタンを表示します。", "攻撃と使用ボタン内に 1 秒あたりのクリック数を表示します。", "スニークとダッシュのキーを 1 行で表示します。",
  "各キーが 1 秒に何回入力されたかを表示します。長押しはキーリピートとして数えます。",
  "1 秒あたりのクリック数がこの値に達すると CPS が赤くなります。",
  "各キーの後ろに背景を描きます。", "キー背景の透け具合。", "各キーの角を丸くします。", "文字の下に影を描きます。",
  "押したときにキーがなめらかに光ります。", "文字が虹色に変化します。", "攻撃と使用がキーボードに割り当てられていても LMB / RMB と表示します。CPS はそのキー（キーリピート含む）を数えます。",
  "HUD を好きな場所へドラッグ。端と中央に吸着します。", "クリックで色を切り替えます。",
  "HUD をドラッグ • Esc で保存", "[KeyCPS] %s を押すと HUD をカスタマイズできます（Mod Menu からも可）。",
  "白", "黒", "灰", "赤", "オレンジ", "黄", "黄緑", "緑", "水色", "青", "紫", "ピンク"],
"ko_kr": ["KeyCPS", "설정 열기", "HUD 이동", "HUD 표시 전환", "KeyCPS 설정",
  "HUD 표시", "크기", "WASD 키", "점프 바", "공격 / 사용", "CPS 카운터", "웅크리기 / 달리기", "키별 횟수", "CPS 경고",
  "배경", "배경 불투명도", "배경 색", "글자 색", "누름 색", "둥근 모서리", "글자 그림자", "누름 애니메이션", "무지개 글자", "항상 LMB / RMB",
  "HUD 이동", "모두 초기화",
  "오버레이 전체를 표시하거나 숨깁니다.", "HUD가 그려지는 크기입니다.", "W, A, S, D 키를 표시합니다.", "점프 키를 바로 표시합니다.",
  "공격 및 사용 버튼을 표시합니다.", "공격 및 사용 버튼 안에 초당 클릭 수를 표시합니다.", "웅크리기와 달리기 키 줄을 표시합니다.",
  "각 키가 초당 몇 번 입력되는지 표시합니다. 키를 누르고 있으면 키 반복 속도를 셉니다.",
  "초당 클릭 수가 이 값 이상이면 CPS가 빨간색이 됩니다.",
  "각 키 뒤에 배경을 그립니다.", "키 배경의 투명도입니다.", "각 키의 모서리를 둥글게 합니다.", "글자 아래에 그림자를 그립니다.",
  "누를 때 키가 부드럽게 켜지고 꺼집니다.", "글자가 무지개 색으로 바뀝니다.", "공격과 사용이 키보드 키에 할당되어 있어도 LMB와 RMB로 표시합니다. CPS는 여전히 해당 키를 반복 입력까지 셉니다.",
  "HUD를 원하는 곳으로 끌어 놓으세요. 가장자리와 중앙에 맞춰집니다.", "클릭하여 색을 바꿉니다.",
  "HUD 끌기 • Esc로 저장", "[KeyCPS] %s 키를 눌러 HUD를 설정하세요 (또는 Mod Menu 사용).",
  "흰색", "검은색", "회색", "빨간색", "주황색", "노란색", "연두색", "초록색", "청록색", "파란색", "보라색", "분홍색"],
}

def entries(v):
    t = dict(zip(KEYS, v))
    out = {
        "key.categories.keycps.keybinds": t["cat"],
        "key.category.keycps.keybinds": t["cat"],
        "key.keycps.open_config": t["open_config"],
        "key.keycps.move_hud": t["move_hud"],
        "key.keycps.toggle_hud": t["toggle_hud"],
        "keycps.config.title": t["title"],
    }
    for k in ["enabled", "scale", "movement", "jump", "mouse", "cps", "sneak_sprint", "key_rates", "cps_warn",
              "background", "bg_opacity", "bg_color", "text_color", "pressed_color", "rounded", "shadow", "fade",
              "rainbow", "mouse_labels", "move", "reset"]:
        out["keycps.config." + k] = t[k]
        if "t_" + k in t:
            out["keycps.config." + k + ".tooltip"] = t["t_" + k]
    out["keycps.config.color.tooltip"] = t["t_color"]
    out["keycps.move.title"] = t["move"]
    out["keycps.move.hint"] = t["move_hint"]
    out["keycps.welcome"] = t["welcome"]
    for c in ["white", "black", "gray", "red", "orange", "yellow", "lime", "green", "aqua", "blue", "purple", "pink"]:
        out["keycps.color." + c] = t[c]
    return out

d = pathlib.Path(__file__).resolve().parent.parent / "src/main/resources/assets/keycps/lang"
for lang, v in L.items():
    assert len(v) == len(KEYS), (lang, len(v), len(KEYS))
    (d / f"{lang}.json").write_text(json.dumps(entries(v), ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(len(L), "languages written")
